name: Build Docker Images
on:
  push:
    paths:
    - 'build/i686-cc/**'
jobs:
  push-to-ghcr:
    name: Build and Push to the github container repository
    runs-on: ubuntu-latest
    steps:
      - name: check out the repo
        uses: actions/checkout@v3

      - name: Login to ghcr
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images
        run: |
          docker build build/i686-cc --tag ghcr.io/aleconte/i686-cc:latest
          docker push ghcr.io/aleconte/i686-cc:latest